### ISSUE TITLE
docs folder

### ISSUE THREAD

**Issue by rosstox26** [nklobo-mban/EffectiveCommunication#1]
Your output is right now going to a _book folder. You need to push the output to a "docs" folder for GitHub pages to pick it up as a n HTML site.

Check the last line of this file: https://github.com/rorymeyer/KRYRK/blob/main/_bookdown.yml

**Comment by zyzaptain** [comment]
> Your output is right now going to a _book folder. You need to push the output to a "docs" folder for GitHub pages to pick it up as an HTML site.
> 
> Check the last line of this file: https://github.com/rorymeyer/KRYRK/blob/main/_bookdown.yml

Thank you for your kind reminder! I have changed the output path and it goes to the docs folder now. But I have a quick question about what "GitHub pages to pick it up as an HTML site" mean?

**Comment by rosstox26** [comment]
Your published site should show up here: https://nklobo-mban.github.io/EffectiveCommunication

As you can see, it is not displaying your site. I imagine you might not have set up GitHub pages yet. Go to Settings -> Pages and choose Main branch and docs folder as the location of your pages. After that the link above should show your published site.

**Comment by rosstox26** [comment]
Its showing up now - beautiful! I am closing this issue now.

**Comment by zyzaptain** [comment]
Great thanks to you!
